# Generated by Django 3.2.12 on 2022-02-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('game_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
